openapi: 3.0.1
info:
  title: Account User
  description: APIs for Shareholder
  version: 1.0.0
paths:
  /accountUser:
    post:
      tags:
        - Account User
      summary:  Create a New Account User
      description: Create a New Account User
      operationId: createAccountUser
      requestBody:
          $ref: '#/components/requestBodies/createAccountUserRequest'
      responses:
        '200':
          $ref: '#/components/responses/createAccountUserResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /accountUser/get:
    get:
      tags:
        - Account User
      summary:  Fetch an accountUser
      description: Fetch an accountUser
      operationId: fetchAccountUser
      parameters:
        - $ref: '#/components/parameters/corporateId'
      responses:
        '200':
          $ref: '#/components/responses/fetchAccountUserResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /accountUser/{accountUserId}:
    delete:
      tags:
        - Account User
      summary:  delete an accountUser
      description: delete an accountUser
      operationId: deleteAccountUser
      parameters:
        - $ref: '#/components/parameters/accountUserId'
      responses:
        '200':
          description: Account User deleted successfully
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'

components:
  schemas:
    createAccountUserRequest:
      type: object
      properties:
        individual: 
          type: string
          format: string
        corporateName:
          type: string
          format: string
        entityStatus:
          type: integer
          format: number
        jobTitle: 
          type: string
          format: string
    createAccountUserResponse:
      type: object
      properties:
        accountUserId:
          type: string
          format: string
    fetchAccountUserResponse:
      type: object
      properties:
        accountUserId:
          type: string
          format: string
        IndividualId:
          type: string
          format: string
        jobTitle:
          type: string
          format: string
        corporateNameId:
          type: string
          format: string
        entityStatus:
          type: integer
          format: number
    HTTPError:
      type: object
      properties:
        status_code:
          type: string
          format: string
        status:
          type: string
          format: string
        message:
          type: string
          format: string
    
  parameters:
    corporateId:
      name: corporateId
      in: query
      required: true
      schema:
        type: string
    accountUserId:
      name: accountUserId
      in: path
      required: true
      schema:
        type: string
  requestBodies:
    createAccountUserRequest:
      required: true
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/createAccountUserRequest'
  responses:
    fetchAccountUserResponse:
        description: fetchAccountUser
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/fetchAccountUserResponse' 
    createAccountUserResponse:
        description: Account user created
        content:
          application/json:
            schema:
                $ref: '#/components/schemas/createAccountUserResponse' 
    BadRequest:
      description: BadRequest
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    Forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    NotFound:
      description: NotFound
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    TooManyRequests:
      description: TooManyRequests
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
    InternalServerError:
      description: InternalServerError
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HTTPError'
